<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.GitHub.Models" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.AspNetCore" />
		<PackageReference Include="Grpc.Core" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Grpc.Net.ClientFactory" />
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Tools">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NATS.Client" />
        <PackageReference Include="NATS.Client.JetStream" />
        <PackageReference Include="NATS.Net" />
        <PackageReference Include="Scrutor" />
	</ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\AuthService.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\RoleService.proto" GrpcServices="Client" />
    </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	</ItemGroup>

</Project>