<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.GitHub.Models" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Grpc.Core" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />

    <PackageReference Include="NATS.Client" />
    <PackageReference Include="NATS.Client.JetStream" />
    <PackageReference Include="NATS.Net" />

    <PackageReference Include="Scrutor" />
  </ItemGroup>

</Project>
